name: DropParty
version: ${project.version}
description: The Drop Party plugin for Bukkit.
author: ampayne2
main: us.divinerealms.neon.dropparty.DropParty
load: POSTWORLD
softdepend: [Votifier]
commands:
  dropparty:
    aliases: [dp, dparty]